### ISSUE TITLE
“注意代码规范啊亲”改为可配置

### ISSUE THREAD

**Issue by CarterLi** [eleme/finite#2]
好烦啊，干掉它又出来
https://github.com/eleme/finite/blob/master/Makefile.d/lint

**Comment by CarterLi** [comment]
Doc? @YanagiEiichi

**Comment by YanagiEiichi** [comment]
.codingstylejoy = DISABLED

**Comment by YanagiEiichi** [comment]
加在项目的 Makefile 中

**Comment by YanagiEiichi** [comment]
@CarterLi  过段时间我补一个完整的文档吧。。这个项目确实缺文档。。#3
